INSERT INTO inventory (id, sku, quantity, reserved_quantity, created_at, updated_at) VALUES 
(1, 'LAP-TITAN-16', 50, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'LAP-AERO-14', 75, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'AUD-SONIC-NC', 120, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'AUD-STUDIO-EAR', 200, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'PHN-APEX-5G', 90, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'WBL-PULSE-PRO', 85, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'WBL-FIT-BAND', 150, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 'MON-CURVED-34', 40, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
